// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinecraftServerScanner.Server;

namespace MinecraftServerScanner.Server.Migrations
{
    [DbContext(typeof(MincraftContext))]
    [Migration("20181220003921_UpdateMinecraftServersTable")]
    partial class UpdateMinecraftServersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MinecraftServerScanner.Server.Models.MinecraftServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Data");

                    b.Property<string>("Host");

                    b.Property<DateTime>("LastOnline");

                    b.Property<bool>("Online");

                    b.Property<short>("Port");

                    b.Property<DateTime>("Scanned");

                    b.HasKey("Id");

                    b.ToTable("MinecraftServers");
                });

            modelBuilder.Entity("MinecraftServerScanner.Server.Models.ReservedNetworkBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CIDR");

                    b.Property<DateTime>("Created");

                    b.HasKey("Id");

                    b.ToTable("ReservedNetworkBlocks");
                });

            modelBuilder.Entity("MinecraftServerScanner.Server.Models.ScannableNetworkBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CIDR");

                    b.Property<DateTime>("Created");

                    b.Property<int>("State");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("ScannableNetworkBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
