// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinecraftServerScanner.Server;

namespace MinecraftServerScanner.Server.Migrations
{
    [DbContext(typeof(MincraftContext))]
    partial class MincraftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MinecraftServerScanner.Server.Models.ReservedNetworkBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CIDR");

                    b.Property<DateTime>("Created");

                    b.HasKey("Id");

                    b.ToTable("ReservedNetworkBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
